init:
- ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { $env:TAG_VERSION = "$env:APPVEYOR_REPO_TAG_NAME.$env:APPVEYOR_BUILD_NUMBER" } else { $env:TAG_VERSION = "v8.2.0.$env:APPVEYOR_BUILD_NUMBER-alpha" }
- ps: $env:TAG_VERSION = $env:TAG_VERSION -replace 'v',''
- ps: Write-Host "Setting version to '$env:TAG_VERSION'"
- ps: Update-AppveyorBuild -Version "$env:TAG_VERSION"

environment:
  matrix:
  - job_name: Linux Build
    platform: x64
    appveyor_build_worker_image: Ubuntu
    configuration: RESTbot

matrix:
  allow_failures:
  - image: Ubuntu

nuget:
  disable_publish_on_pr: true

build:
  publish_nuget: false
  publish_nuget_symbols: false
  use_snupkg_format: true
  parallel: true
  verbosity: minimal

before_build:
  - dotnet --info
  - dotnet restore RESTbot.csproj

for:
  -
    matrix:
      only:
        - job_name: Linux Build