version: 8.2.0.{build}

environment:
	matrix:
	- job_name: Linux Build
		platform: x64
		appveyor_build_worker_image: Ubuntu
		configuration: RESTbot

matrix:
	allow_failures:
	- image: Ubuntu

# nuget:
# 	disable_publish_on_pr: true

build:
	publish_nuget: false
	publish_nuget_symbols: false
	use_snupkg_format: true
	parallel: true
	verbosity: minimal

before_build:
	- dotnet --info
	- dotnet restore RESTbot.sln
