version: 8.2.0.{build}
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  parallel: true
  verbosity: minimal

environment:
	matrix:
	- job_name: Linux Build
		platform: x64
		appveyor_build_worker_image: Ubuntu
		configuration: RESTbot

matrix:
	allow_failures:
	- image: Ubuntu

nuget:
	disable_publish_on_pr: true

before_build:
	- dotnet --info
	- dotnet restore RESTbot.sln
